### ISSUE TITLE
RxODE to rxode2?

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/dparser-R#10]
Should the RxODE reference here become rxode2?  (I realize that the paper refers to RxODE, but I thought I'd mention it for consideration.)

https://github.com/nlmixr2/dparser-R/blob/bc20dcafdeb06ea17a5f9ff4cf25dd5bcc0feb80/DESCRIPTION#L19

**Comment by mattfidler** [comment]
Probably.

**Comment by mattfidler** [comment]
done in pull request
