### ISSUE TITLE
R code to BNF

### ISSUE THREAD

**Issue by mytarmail** [nlmixr2/dparser-R#12]
Hello! I know very little about parsers and everything else, which is why my question might be stupid.

I need to translate R code into BNF grammar, can I do it with your package?
If so, I would be very grateful for a small example
Thank you.

**Comment by mattfidler** [comment]
I'm sorry, but I am unsure what a `BNF` grammar is.  While I use this package, I mostly ported it from the original dparser.

If you are looking for a R-like grammar, you can see what `rxode2` uses:

https://github.com/nlmixr2/rxode2/blob/main/inst/tran.g
